### ISSUE TITLE
True False capitalisation issues

### ISSUE THREAD

**Issue by nik-hz** [Barnard-PL-Labs/tsl-api#2]
The api does not accept lowercase true and false only True and False. 

```
    comeAlive(index) -> [alive <- True];
```

Works whereas

```
    comeAlive(index) -> [alive <- true];
```

throws 

```
Command failed: tsl synthesize -i tmp.tsl --js
tsl: "True" cannot be part of an AST.
CallStack (from HasCallStack):
  error, called at src/TSL/HOA/Codegen.hs:198:29 in tsl-2.0.0.0-9Ku6Ii70Jk0421RpU1dhV9:TSL.HOA.Codegen
```

**Comment by santolucito** [comment]
The core of this issue is discussed here: https://github.com/Barnard-PL-Labs/tsltools/issues/58

As a stopgap, it may be nice to add a preprocessor and throw a warning if we see either true or True in the spec. Really neither should be there (yet).

I would rather not put this in the tsl-api since I want to keep this as the tiniest wrapper possible. It would be better to put this in tsltools, similar to here: https://github.com/Barnard-PL-Labs/tsltools/blob/57a1d8968e29b51e35e06deea6d2262b4ed3cefb/src/TSL/Preprocessor.hs#L458

**Comment by santolucito** [comment]
closing in favor of https://github.com/Barnard-PL-Labs/tsltools/issues/58
